apiVersion: v1
kind: Pod
metadata:
  name: centos-pod-2
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pvc-claim-centos
  containers:
    - name: task-pv-container
      image: centos:latest
      command: ["/bin/sleep", "3650d"]
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mnt/data"
          name: task-pv-storage