apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      volumes:
        -name: task-pv-storage
        persistentVolumeClaim:
          claimName: pvc-claim-2
      containers:
      - name: centos
        image: centos:latest
        command: ["/bin/sleep", "3650d"]
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/mnt/datadrive"
            name: task-pv-storage

