apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-centos
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sass273491/kubedata"
